### ISSUE TITLE
Does not work at all even with old version of cemu

### ISSUE THREAD

**Issue by alpha7504** [quinton-ashley/cemu-no-gyro#10]
Hello,

First of all thanks for this piece of software.. I just heard about it recently, thought should give it a try. I first tried with recent cemu, 1.25.0, and it didn't work. I saw again that it doesn't work with version above 1.20.0+, so i tried with 1.19.0... And it doesn't work with that too.

Unless i am doing something wrong here or it just doesn't work with 1.19.0. What's the last version it worked ok with?

I am trying to control the motion controls with my controller's right stick. I have a direct input game controller.

I use xoutput to emulate xinput controller.. cemu-no-gyro detects the controller, and says gamepad connected. DSU slot is already set in cemu options but motion controls aren't working at all.

Kindly share your thoughts...

Regards!

**Comment by quinton-ashley** [comment]
I think it worked with 1.16

**Comment by quinton-ashley** [comment]
Fixed in v1.1.0
