### ISSUE TITLE
Can't get it to work with cemu 1.22.7

### ISSUE THREAD

**Issue by Zyles** [quinton-ashley/cemu-no-gyro#11]
Controller connected, phone connected. But nothing happening in game.

![image](https://user-images.githubusercontent.com/1741593/153815160-cf5ac4e2-95e7-4093-a422-b8fbb6239221.png)

![image](https://user-images.githubusercontent.com/1741593/153815189-05215073-cd34-44d7-a1bc-5d1faf76cc85.png)

**Comment by quinton-ashley** [comment]
hmm it might not work anymore with the latest version of cemu

**Comment by quinton-ashley** [comment]
Solved by PR #16 ! Try v1.1.2
