### ISSUE TITLE
nothing works.

### ISSUE THREAD

**Issue by metrogo10** [quinton-ashley/cemu-no-gyro#12]
so after allot of trial and error I am unable to get this program working. I cant seem to figure out your instructions. cemu or cemuhook auto detected your program but it does not behave the way your readme says. it will not detect a controller no matter what I do. the readme says that there is some sort of window I need to keep open in the background but no window pops up and there is no exe I can click to open a window. I tried using the software you linked to enable phone motion and when I ran that it seemed like everything was being detected but nothing I did with the phone caused any action in game and the values describing phone position on the site never adjusted. I'm on android so idk what the problem is since all of the troubleshooting info on that site is for ios. Is there a special place I need to unpack the files to get this mystery window to pop up? Is there some other third party program I need that isn't mentioned in the readme? I've spent a long time trying to get motion controls working on this I tried using ds4 for windows but after uninstalling and reinstalling every version of .net runtime that has ever existed several times it still refused to acknowledge that I had it and wouldn't run so I've got nothing left but this. please help.

**Comment by quinton-ashley** [comment]
Yeah it might not work anymore with the latest version of cemu. When you download this program and install it you should see the cemu-no-gyro window open though.

**Comment by quinton-ashley** [comment]
solved by PR #16 !
