### ISSUE TITLE
No motion controls detected in game

### ISSUE THREAD

**Issue by alexnavas1** [quinton-ashley/cemu-no-gyro#13]
Playing BOTW with a wired xbox one controller on windows 10 with 1.26.2f cemu and up-to-date cemuhook also. No issues with controller at all. Installed the exe file and ran it and CEMU detects the program in the DSU1 port but it has no effect on the game. Tried using "by MAC" rather than "by slot" in case that could somehow change it but no difference. I appreciate someone else recently commented on the application not working for them too but I thought I should give my own experience using it just in case it helps to shed any light on the underlying issue for you.

**Comment by quinton-ashley** [comment]
Sorry it seems like the app doesn't work anymore. Thanks for reporting the issue.

**Comment by quinton-ashley** [comment]
solved by PR #16 !
