### ISSUE TITLE
phone motion is un usable due to http connection.

### ISSUE THREAD

**Issue by lmst2** [quinton-ashley/cemu-no-gyro#14]
hey there I find that the motion not working on my phone (all x,y,z are zero) and I checked your code sees you use window.ondevicemotion lisenner. and after checking on the internet I see [this](https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events/Detecting_device_orientation)
![image](https://user-images.githubusercontent.com/29498103/230765891-c4fe6627-a426-478d-81b8-bd7003969362.png)
![image](https://user-images.githubusercontent.com/29498103/230765895-8f5e3b7a-9cc2-46a5-afef-0cf0f4ffe81d.png)
it says the motion detection feature are disabled on not secure context like connection through http. it will only work through https connection. could you guys somehow establish a https connection? since I am not farmilar with js.

**Comment by quinton-ashley** [comment]
Sorry but there's no way to establish an https connection as far as I know. Seems like this app doesn't work anymore.

**Comment by quinton-ashley** [comment]
solved by PR #16 !
