### ISSUE TITLE
App still works with Cemu 1.X.X, just not the phone part

### ISSUE THREAD

**Issue by davidsch22** [quinton-ashley/cemu-no-gyro#15]
I was looking for a program like this for a long time cause I figured a solution to emulate gyro movement with the controller was a no-brainer. But then I see the README and look through the issues and it appears that you've given up on this project... even though the part of the app without using a phone still works perfectly fine. The people who said they couldn't get it to work clearly just didn't set it up correctly.

The issue regarding a phone's connection with HTTPS was a good catch, but I'll bet it's an easier fix than you think.

I just wanted to bring this to your attention. If you really just don't want to continue working on this, that's fine. Maybe I'll fork it for myself.

**Comment by quinton-ashley** [comment]
oh okay good to know!

Seems like it's impossible for the phone thing to work though unless the data was passed through a https website.

**Comment by quinton-ashley** [comment]
solved by PR #16 !
