### ISSUE TITLE
Cannot find module 'contro-ui'

### ISSUE THREAD

**Issue by Matheus-Rangel** [quinton-ashley/cemu-no-gyro#17]
I tested the release and for some reason is given this error now. 
![cemu-no-gyro-error](https://github.com/quinton-ashley/cemu-no-gyro/assets/10068020/40bf9f08-8b85-462b-9fa9-a221a3cc2a05)

**Comment by Matheus-Rangel** [comment]
I noticed that you did not have electron builder or electron on the requirements, which version was you using?

**Comment by quinton-ashley** [comment]
@Matheus-Rangel Aw yeah contro-ui was not in package.json I will fix that. But I also noticed that the https link didn't fully work, Chrome gave me a warning saying the site was not secure.

<img width="569" alt="Screenshot 2023-05-28 at 12 48 23" src="https://github.com/quinton-ashley/cemu-no-gyro/assets/20031683/95b1fac8-072d-47d0-a344-f8426329dee5">
<img width="360" alt="Screenshot 2023-05-28 at 12 48 31" src="https://github.com/quinton-ashley/cemu-no-gyro/assets/20031683/c17ab4a8-ad48-4599-9ccf-43dcc5da1b7b">

**Comment by Matheus-Rangel** [comment]
Yeah the warning will be present because it is a self signed certificate, it's impossible to remove that warning without a domain and paying for the certificate. But you can skip and access anyway

**Comment by quinton-ashley** [comment]
Oh okay got it. If you skip the warning it does work! :)

I just uploaded v1.1.5
