### ISSUE TITLE
No URL for phone connection 

### ISSUE THREAD

**Issue by RemyBorius** [quinton-ashley/cemu-no-gyro#19]
I'm on cemu no gyro 1.1.3

I suppose this new release is to fix the defective phone connection, so I wanted to try it.

The problem is that in the interface of cemu no gyro, there is no URL for the phone has it was on cemu no gyro 1.1.1

![image](https://github.com/quinton-ashley/cemu-no-gyro/assets/83087445/a0f54530-1a02-4a19-adaf-0fe723306266)

also, the HOW TO section is not here any more.

**Comment by lrutjens** [comment]
i have the same issue

**Comment by lrutjens** [comment]
I ended up just cloning the repo and running it with npm, then the setup and links appear. The link should be [https://your-pc-ip:8443](https://172.0.0.1:8443)

**Comment by quinton-ashley** [comment]
@lrutjens @RemyBorius  hm on macOS when I tested the app it had some errors but I guess it pushed through and still worked lol

Seems that's not that case on windows though.

I just uploaded a new version, let me know if it works!
