### ISSUE TITLE
Request for JSON Template or Sample Code for Sending Gyro Data to Cemu-No-Gyro App with Python

### ISSUE THREAD

**Issue by kgncengiz** [quinton-ashley/cemu-no-gyro#21]
My friend and I have been working on using Python to send gyro data to the Cemu-No-Gyro app for several hours (6-8). However, we are struggling to find the JSON file template that we need to use. Could you provide us with the JSON file template, or even better, a sample code?

**Comment by quinton-ashley** [comment]
No but you can see how the data is sent in this file:
https://github.com/quinton-ashley/cemu-no-gyro/blob/main/views/js/client.js

Good luck!
