### ISSUE TITLE
Permenantly altered joystick range after using Cemu-no-gyro

### ISSUE THREAD

**Issue by zachHixson** [quinton-ashley/cemu-no-gyro#4]
After using Cemu-no-gyro with the left joystick on my 360 controller to control the motion, the _up_ direction on the controller now only outputs about 20% "Force," or whatever you want to call it, meaning trying to move the camera in that direction is now painfully slow while all other directions work fine. 

Good news is that this issue is only linked to cemu and doesn't affect any other games outside of cemu, but it's still a huge annoyance. I can seemingly fix it by upping the "Range," in Cemu, but then after I use cemu-no-gyro again it causes the same issue and I have to go back and up the range even more.

**Comment by quinton-ashley** [comment]
this probably isn't an issue with cemu-no-gyro, try using Xinput in Cemu's controller settings
http://compat.cemu.info/wiki/Tutorial:Configuring_Controllers

**Comment by zachHixson** [comment]
XInput makes no difference. It's definately something to do with the interraction of Cemu and cemu-no-gryo. I looked at your code, and it doesn't appear that cemu-no-gryo is editing any Cemu files directly so your probably right about it being an internal Cemu problem.

**Comment by quinton-ashley** [comment]
which version of cemu and cemuhook are you using?

**Comment by zachHixson** [comment]
0.5.7.3

**Comment by quinton-ashley** [comment]
I don't know what could be causing that I'm sorry.  I use an Xbox One controller with the same version of cemuhook.
