### ISSUE TITLE
Raw-value mode?

### ISSUE THREAD

**Issue by ArsenicBismuth** [quinton-ashley/cemu-no-gyro#6]
Is it possible to add a feature to input raw-value from the analog axis? So, an `X` value directly translates to `cX` yaw for example (with `c` just a constant for sensitivity). ~~This way, the rotation is not incremental but absolute~~*.

Or maybe some pointers or ideas for me to achieve this, since I'm going to fork this anyway to add accelerometer control.

*EDIT: Brainfart, forgot gyro gives angular velocity, thus it should behave like analog stick (both input rate of rotational position change), if the value is given raw. So all that's left is making sure the gyro input and program output (to Cemuhook) is 1:1, and adding accelerometer support. 

---

In case you're wondering what I'm trying to do: sending a DIY IMU-Arduino data to Cemu. I already managed to get the data and turn it into a fake controller (gyro & accel data as analog axis). So all that's left is communicating through Cemuhook.

**Comment by quinton-ashley** [comment]
Oh my, it's been a while since I worked on this project haha.  I have a few questions. Why convert real gyro and accel data to the analog axes of a fake controller?  How are you doing that?  Does the fake controller connect to cemu-no-gyro?

**Comment by ArsenicBismuth** [comment]
> Why convert real gyro and accel data to the analog axes of a fake controller?

Well, that's the most versatile way to do it. The Arduino is seen as a simple controller HID and I can use it on generic programs that'd accept joystick input like yours (Assetto Corsa is another great example, it's highly customizable, but ofc it'd only accept devices recognized as HID by Windows).

Otherwise I'd be dealing with raw serial data, which is not exactly usable in a lot of scenario (there're ways to convert serial to fake joystick, but that'd add another layer).

> Does the fake controller connect to cemu-no-gyro?

I couldn't test it for now, but even my old dinput controller works (through x360ce). It shouldn't be a problem.

**Comment by quinton-ashley** [comment]
Does this arduin controller only have a real gyro and acel? no other
buttons or sticks?  Lmk if it connects.

**Comment by ArsenicBismuth** [comment]
My setup is a generic controller + that IMU-Arduino (as a fake controller), so it'd be similar to the controller + phone setup.

If you need a user interaction (ex for confirmation or detection) from the fake controller, it can be easily done by either adding a button to the Arduino or sending a serial command from PC => Arduino => PC (as fake controller).

**Comment by ArsenicBismuth** [comment]
> Lmk if it connects.

The Arduino arrived today, tested through x360ce and your program detects it. Also tested with PadTest, no strange behavior.

Extra: I edited my original issue comment above regarding "raw value".

**Comment by quinton-ashley** [comment]
Good! Does it work as you'd expect then?  Should I close this issue?

**Comment by ArsenicBismuth** [comment]
I'll test it further for now, and close the issue myself if there's no issue with anything related to the data send by the program.

For now, just a casual question, is it true I just need to deal with `views/js/index.js` if I want to deal with the core functionality (ex: add accelerometer control)? Meanwhile most of the other things are for webgyro and UI.

**Comment by ArsenicBismuth** [comment]
Tested and everything seems to be perfect. It's very similar to the Controller + Smartphone setup, only now ofc I don't need to move around a heavy phone. Thx for making my years-old project possible lol.

Repository: https://github.com/ArsenicBismuth/Cemu-GyroStick
