### ISSUE TITLE
v1.016 doesn't seem to work with CEMU 1.20c?

### ISSUE THREAD

**Issue by DeXtmL** [quinton-ashley/cemu-no-gyro#7]
Gamepad and phone are able to connect, Cemuhook successfully detects it, but doesn't affect the actual input at all

**Comment by JailAir2** [comment]
> Gamepad and phone are able to connect, Cemuhook successfully detects it, but doesn't affect the actual input at all

Same issue here

**Comment by quinton-ashley** [comment]
I'll investigate why this happens at some point. Sorry that cemu-no-gyro doesn't work with newer issues of Cemu.

**Comment by quinton-ashley** [comment]
Fixed in v1.1.0
