### ISSUE TITLE
No input detected from pixel 3xl

### ISSUE THREAD

**Issue by maxwell-01** [quinton-ashley/cemu-no-gyro#8]
Hello,

I'm hoping you can help point me in the right direction. I have installed the app and it works well with the controller. I have connected my phone to the IP address and the app reports 'Phone connected!'. However on the phone screen the x,y and z stay at 0 and no input is detected. Am I missing a step? I couldn't see any instructions for getting this to work. Running a pixel 3xl.

Thanks :)

EDIT: I found this thread: https://github.com/hjmmc/WebGyroForCemuhook/releases
I tried that and using HTTPS and port 8443 works. However I'd love to be able to use your program and the sticks as well as the phone.

**Comment by quinton-ashley** [comment]
I have heard other users have similar issues. I'll investigate why this happens at some point. Sorry that cemu-no-gyro doesn't work with newer issues of Cemu.

**Comment by quinton-ashley** [comment]
Fixed in v1.1.0
