### ISSUE TITLE
Does not work at all. 

### ISSUE THREAD

**Issue by TsynkZZZ** [quinton-ashley/cemu-no-gyro#9]
I installed everyting, my Cemu already had the hook installed and using Cemu 1.22.12c. Nothing works, it does not detect my Power A Switch Wired controller, my LG Rebel 4 does not work at all, connects, but the gyro won't budge at all. I am using the right settings,

**Comment by quinton-ashley** [comment]
I have heard other users have similar issues. I'll investigate why this happens at some point. Sorry that cemu-no-gyro doesn't work with newer issues of Cemu.

**Comment by quinton-ashley** [comment]
Fixed in v1.1.0
